export const ABIA = {
    state: "ABIA",
    lga: [
      {
        wards: [
            "ARIARIA MARKET",
            "EZIAMA",
            "INDUSTRIAL AREA",
            "OGBOR I",
            "OGBOR II",
            "OLD ABA GRA",
            "OSUSU I",
            "OSUSU II",
            "ST.EUGENES BY OKIGWE RD.",
            "UMUOGOR",
            "UMUOLA",
            "URATTA"
        ],
        name: "ABA NORTH",
      },
      {
        wards: [
            "ABA RIVER",
            "ABA TOWN HALL",
            "ASA",
            "EKEOHA",
            "ENYIMBA",
            "EZIUKWU",
            "GLOUCESTER",
            "IGWEBUIKE",
            "MOSQUE",
            "NGWA",
            "OHAZU I",
            "OHAZU II"
        ],
        name: "ABA SOUTH",
      },
      {
        wards: [
            "AROCHUKWU I",
            "AROCHUKWU II",
            "AROCHUKWU III",
            "ELEOHA IHECHIOWA",
            "IKWUN IHECHIOWA",
            "ISU",
            "OHAEKE",
            "OHAFOR I",
            "OHAFOR II",
            "OVUKWU",
            "UTUTU"
        ],
        name: "AROCHUKWU",
      },
      {
        wards: [
            "AMANKALU/AKOLIUFU",
            "BENDE",
            "IGBERE 'A'",
            "IGBERE 'B'",
            "ITEM A",
            "ITEM B",
            "ITEM C",
            "ITUMBAUZO",
            "OZUITEM",
            "UGWUEKE/EZEUKWU",
            "UMU - IMENYI",
            "UMUHU / EZECHI",
            "UZUAKOLI"
        ],
        name: "BENDE",
      },
      {
        wards: [
            "ARIAM",
            "IBERE I",
            "IBERE II",
            "OBORO I",
            "OBORO II",
            "OBORO III",
            "OBORO IV",
            "OLOKO I",
            "OLOKO II",
            "USAKA"
        ],
        name: "IKWUANO",
      },
      {
        wards: [
            "AMAPU NTIGHA",
            "AMASAA NSULU",
            "AMASAA NTIGHA",
            "IHIE",
            "ISIALA NSULU",
            "MBAWSI / UMUOMAINTA",
            "NGWA UKWU I",
            "NGWA UKWU II",
            "UMUNNA NSULU",
            "UMUOHA",
            "AKUNEKPU EZIAMA NA OBUBA",
            "AMAISE / AMAISE ANABA",
            "EHINA GURU OSOKWA",
            "MBUTU NGWA",
            "MBUTU UKWU",
            "NGWAOBI",
            "OKPORO AHABA",
            "OMOBA",
            "OVUNGWU",
            "OVUOKWU"
        ],
        name: "ISIALA NGWA NORTH",
      },
      {
        wards: [
            "ACHARA / MGBUGWU",
            "EZERE",
            "IKEAGHA I",
            "IKEAGHA II",
            "IMENYI",
            "ISIALA AMAWU",
            "ISU AMAWU",
            "OGUNDUASA",
            "UMUANYI / ABSU",
            "UMUNNEKWU"
        ],
        name: "ISUIKWUATO",
      },
      {
        wards: [
            "ABAYI I",
            "ABAYI II",
            "AHIABA",
            "AKUMAIMO",
            "ALAUKWU OHANZE",
            "IBEME",
            "MABOKO AMAIRI",
            "MGBOKO ITUNGWA",
            "MGBOKO UMUANUNU",
            "NDIARATA / AMAIRINABUA",
            "NTIGHAUZO AMAIRI"
        ],
        name: "OBINGWA",
      },
      {
        wards: [
            "AGBOJI ABIRIBA",
            "AMAEKE ABIRIBA",
            "AMAOGUDU ABIRIBA",
            "ANIA OHOAFIA",
            "EBEM OHAFIA",
            "ISIAMA OHAFIA",
            "NDI AGBO NKPORO",
            "NDI ELU NKPORO",
            "NDI ETITI NKPORO",
            "OHAFOR OHOAFIA",
            "OKANU OHOAFIA"
        ],
        name: "OHAFIA",
      },
      {
        wards: [
            "AMA - ASAA",
            "AMAITOLU MBUTU UMUOJIMA",
            "AMASATOR",
            "AMATOR",
            "AMAVO",
            "ARO - NGWA",
            "OKPOR - UMUOBO",
            "OSO - OKWA",
            "UMUNNEISE",
            "URTTA"
        ],
        name: "OSISIOMA",
      },
      {
        wards: [
            "WARD EIGHT",
            "WARD FIVE",
            "WARD FOUR",
            "WARD NINE",
            "WARD ONE",
            "WARD SEVEN",
            "WARD SIX",
            "WARD TEN",
            "WARD THREE",
            "WARD TWO"
        ],
        name: "UGWUNAGBO",
      },
      {
        wards: [
            "ASA NORTH",
            "ASA SOUTH",
            "IPU SOUTH",
            "IPU EAST",
            "IPU WEST",
            "OBOKWE",
            "OBUZOR",
            "OGWE",
            "OZAA WEST",
            "OZAA UKWU"
        ],
        name: "UKWA WEST",
      },
      {
        wards: [
            "AKWETE",
            "AZUMINI",
            "IKWUEKE WEST",
            "IKWUEKE EAST",
            "IKWUORIE",
            "IKWURIATOR EAST",
            "IKWURIATOR WEST",
            "NKPOROBE/OHURU",
            "OBOHIA",
            "UMUIGUBE ACHARA"
        ],
        name: "UKWA EAST",
      },
      {
        wards: [
            "AMUDA",
            "EZIAMA - AGBO",
            "EZIAMA - UGWU",
            "EZINGODO",
            "MBALA/ACHARA",
            "NDIAWA/UMUELEM/I",
            "OBINOLU/OBIAGU/LA",
            "UBAHU/AKAWA/AROKPA",
            "UMUAKU",
            "UMUCHIEZE I",
            "UMUCHIEZE II",
            "UMUCHIEZE III"
        ],
        name: "UMU - NNEOCHI",
      },
      {
        wards: [
            "AHIAUKWU I",
            "AHIAUKWU II",
            "AMAKAMA",
            "EZELEKE/OGBODIUKWU",
            "NSIRIMO",
            "OHIAOCHA",
            "OLD UMUAHIA",
            "OMAEGWU",
            "UBAKALA 'A'",
            "UBAKALA 'B'"
        ],
        name: "UMUAHIA SOUTH",
      },
      {
        wards: [
            "AFUGIRI",
            "IBEKU EAST I",
            "IBEKU EAST II",
            "IBEKU WEST",
            "ISINGWU",
            "NDUME",
            "NKWOACHARA",
            "NKWOEGWU",
            "UMUAHIA URBAN I",
            "UMUAHIA URBAN II",
            "UMUAHIA URBAN III",
            "UMUHU"
        ],
        name: "UMUAHIA NORTH",
      },
    ],
  };
  