export const BORNO = {
  state: "BORNO",
  lga: [
    { wards: [], name: "Abadam" },
    { wards: [], name: "Askira/Uba" },
    { wards: [], name: "Bama" },
    { wards: [], name: "Bayo" },
    { wards: [], name: "Biu" },
    { wards: [], name: "Chibok" },
    { wards: [], name: "Damboa" },
    { wards: [], name: "Dikwa" },
    { wards: [], name: "Gubio" },
    { wards: [], name: "Guzamala" },
    { wards: [], name: "Gwoza" },
    { wards: [], name: "Hawul" },
    { wards: [], name: "Jere" },
    { wards: [], name: "Kaga" },
    { wards: [], name: "Kala/Balge" },
    { wards: [], name: "Konduga" },
    { wards: [], name: "Kukawa" },
    { wards: [], name: "Kwaya Kusar" },
    { wards: [], name: "Mafa" },
    { wards: [], name: "Magumeri" },
    { wards: [], name: "Maiduguri" },
    { wards: [], name: "Marte" },
    { wards: [], name: "Mobbar" },
    { wards: [], name: "Monguno" },
    { wards: [], name: "Ngala" },
    { wards: [], name: "Nganzai" },
    { wards: [], name: "Shani" },
  ],
};
