export const DELTA = {
  state: "DELTA",
  lga: [
    { wards: [], name: "Aniocha North" },
    { wards: [], name: "Aniocha South" },
    { wards: [], name: "Bomadi" },
    { wards: [], name: "Burutu" },
    { wards: [], name: "Ethiope East" },
    { wards: [], name: "Ethiope West" },
    { wards: [], name: "Ika North East" },
    { wards: [], name: "Ika South" },
    { wards: [], name: "Isoko North" },
    { wards: [], name: "Isoko South" },
    { wards: [], name: "Ndokwa East" },
    { wards: [], name: "Ndokwa West" },
    { wards: [], name: "Okpe" },
    { wards: [], name: "Oshimili North" },
    { wards: [], name: "Oshimili South" },
    { wards: [], name: "Patani" },
    { wards: [], name: "Sapele" },
    { wards: [], name: "Udu" },
    { wards: [], name: "Ughelli North" },
    { wards: [], name: "Ughelli South" },
    { wards: [], name: "Ukwuani" },
    { wards: [], name: "Uvwie" },
    { wards: [], name: "Warri North" },
    { wards: [], name: "Warri South" },
    { wards: [], name: "Warri South West" },
  ],
};
