export const states = [
  { name: "Abia", statecode: "ABIA" },
  { name: "Akwa Ibom", statecode: "AKWA-IBOM" },
  { name: "Anambra", statecode: "ANAMBRA" },
  { name: "Bauchi", statecode: "ABIA" },
  { name: "Bayelsa", statecode: "ABIA" },
  { name: "Benue", statecode: "ABIA" },
  { name: "Borno", statecode: "ABIA" },
  { name: "Cross River", statecode: "ABIA" },
  { name: "Delta", statecode: "ABIA" },
  { name: "Ebonyi", statecode: "ABIA" },
  { name: "Edo", statecode: "ABIA" },
  { name: "Ekiti", statecode: "ABIA" },
  { name: "Enugu", statecode: "ABIA" },
  { name: "Gombe", statecode: "ABIA" },
  { name: "Imo", statecode: "ABIA" },
  { name: "Jigawa", statecode: "ABIA" },
  { name: "Kaduna", statecode: "ABIA" },
  { name: "Kano", statecode: "ABIA" },
  { name: "Katsina", statecode: "ABIA" },
  { name: "Kebbi", statecode: "ABIA" },
  { name: "Kogi", statecode: "ABIA" },
  { name: "Kwara", statecode: "ABIA" },
  { name: "Lagos", statecode: "ABIA" },
  { name: "Nasarawa", statecode: "ABIA" },
  { name: "Niger", statecode: "ABIA" },
  { name: "Ogun", statecode: "ABIA" },
  { name: "Ondo", statecode: "ABIA" },
  { name: "Osun", statecode: "ABIA" },
  { name: "Oyo", statecode: "ABIA" },
  { name: "Plateau", statecode: "ABIA" },
  { name: "Rivers", statecode: "ABIA" },
  { name: "Sokoto", statecode: "ABIA" },
  { name: "Taraba", statecode: "ABIA" },
  { name: "Yobe", statecode: "ABIA" },
  { name: "Zamfara", statecode: "ABIA" },
  { name: "Federal Capital Territory", statecode: "ABIA" },
];
