export const states = [
  { name: "Abia", statecode: "ABIA" },
  { name: "Adamawa", statecode: "ADAMAWA" },
  { name: "Akwa Ibom", statecode: "AKWA-IBOM" },
  { name: "Anambra", statecode: "ANAMBRA" },
  { name: "Bauchi", statecode: "BAUCHI" },
  { name: "Bayelsa", statecode: "BAYELSA" },
  { name: "Benue", statecode: "BENUE" },
  { name: "Borno", statecode: "BORNO" },
  { name: "Cross River", statecode: "CROSS-RIVER" },
  { name: "Delta", statecode: "DELTA" },
  { name: "Ebonyi", statecode: "EBONYI" },
  { name: "Edo", statecode: "EDO" },
  { name: "Ekiti", statecode: "EKITI" },
  { name: "Enugu", statecode: "ENUGU" },
  { name: "Gombe", statecode: "GOMBE" },
  { name: "Imo", statecode: "IMO" },
  { name: "Jigawa", statecode: "JIGAWA" },
  { name: "Kaduna", statecode: "KADUNA" },
  { name: "Kano", statecode: "KANO" },
  { name: "Katsina", statecode: "KATSINA" },
  { name: "Kebbi", statecode: "KEBBI" },
  { name: "Kogi", statecode: "KOGI" },
  { name: "Kwara", statecode: "KWARA" },
  { name: "Lagos", statecode: "LAGOS" },
  { name: "Nasarawa", statecode: "NASARAWA" },
  { name: "Niger", statecode: "NIGER" },
  { name: "Ogun", statecode: "OGUN" },
  { name: "Ondo", statecode: "ONDO" },
  { name: "Osun", statecode: "OSUN" },
  { name: "Oyo", statecode: "OYO" },
  { name: "Plateau", statecode: "PLATEAU" },
  { name: "Rivers", statecode: "RIVERS" },
  { name: "Sokoto", statecode: "SOKOTO" },
  { name: "Taraba", statecode: "TARABA" },
  { name: "Yobe", statecode: "YOBE" },
  { name: "Zamfara", statecode: "ZAMFARA" },
  { name: "Federal Capital Territory", statecode: "ABUJA" },
];
